Ecole Coranique/Controllers/AbsencesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ecole_Coranique.Data;
using Ecole_Coranique.Models;

namespace Ecole_Coranique.Controllers
{
    public class AbsencesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AbsencesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Absences
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Absences.Include(a => a.Etudiant);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Absences/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var absence = await _context.Absences
                .Include(a => a.Etudiant)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (absence == null)
            {
                return NotFound();
            }

            return View(absence);
        }

        // GET: Absences/Create
        public IActionResult Create()
        {
            ViewData["EtudiantId"] = new SelectList(_context.Etudiants, "Id", "Fullname");
            return View();
        }

        // POST: Absences/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date,Observation,EtudiantId")] Absence absence)
        {
            if (ModelState.IsValid)
            {
                _context.Add(absence);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EtudiantId"] = new SelectList(_context.Etudiants, "Id", "Fullname", absence.EtudiantId);
            return View(absence);
        }

        // GET: Absences/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var absence = await _context.Absences.FindAsync(id);
            if (absence == null)
            {
                return NotFound();
            }
            ViewData["EtudiantId"] = new SelectList(_context.Etudiants, "Id", "Fullname", absence.EtudiantId);
            return View(absence);
        }

        // POST: Absences/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,Observation,EtudiantId")] Absence absence)
        {
            if (id != absence.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(absence);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AbsenceExists(absence.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EtudiantId"] = new SelectList(_context.Etudiants, "Id", "Fullname", absence.EtudiantId);
            return View(absence);
        }

        // GET: Absences/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var absence = await _context.Absences
                .Include(a => a.Etudiant)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (absence == null)
            {
                return NotFound();
            }

            return View(absence);
        }

        // POST: Absences/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var absence = await _context.Absences.FindAsync(id);
            _context.Absences.Remove(absence);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AbsenceExists(int id)
        {
            return _context.Absences.Any(e => e.Id == id);
        }
    }
}

Ecole Coranique/Controllers/GroupesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ecole_Coranique.Data;
using Ecole_Coranique.Models;

namespace Ecole_Coranique.Controllers
{
    public class GroupesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GroupesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Groupes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Groupes.Include(g => g.Enseignant);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Groupes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var groupe = await _context.Groupes
                .Include(g => g.Enseignant)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (groupe == null)
            {
                return NotFound();
            }

            return View(groupe);
        }

        // GET: Groupes/Create
        public IActionResult Create()
        {
            ViewData["EnseignantId"] = new SelectList(_context.Enseignants, "Id", "Fullname");
            return View();
        }

        // POST: Groupes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Numero,Nom,EnseignantId")] Groupe groupe)
        {
            if (ModelState.IsValid)
            {
                _context.Add(groupe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EnseignantId"] = new SelectList(_context.Enseignants, "Id", "Fullname", groupe.EnseignantId);
            return View(groupe);
        }

        // GET: Groupes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var groupe = await _context.Groupes.FindAsync(id);
            if (groupe == null)
            {
                return NotFound();
            }
            ViewData["EnseignantId"] = new SelectList(_context.Enseignants, "Id", "Fullname", groupe.EnseignantId);
            return View(groupe);
        }

        // POST: Groupes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Numero,Nom,EnseignantId")] Groupe groupe)
        {
            if (id != groupe.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(groupe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupeExists(groupe.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EnseignantId"] = new SelectList(_context.Enseignants, "Id", "Fullname", groupe.EnseignantId);
            return View(groupe);
        }

        // GET: Groupes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var groupe = await _context.Groupes
                .Include(g => g.Enseignant)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (groupe == null)
            {
                return NotFound();
            }

            return View(groupe);
        }

        // POST: Groupes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var groupe = await _context.Groupes.FindAsync(id);
            _context.Groupes.Remove(groupe);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GroupeExists(int id)
        {
            return _context.Groupes.Any(e => e.Id == id);
        }
    }
}

Ecole Coranique/Controllers/HizbsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ecole_Coranique.Data;
using Ecole_Coranique.Models;

namespace Ecole_Coranique.Controllers
{
    public class HizbsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HizbsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Hizbs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Hizbs.ToListAsync());
        }

        // GET: Hizbs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hizb = await _context.Hizbs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hizb == null)
            {
                return NotFound();
            }

            return View(hizb);
        }

        // GET: Hizbs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Hizbs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Numero,Nom,Description")] Hizb hizb)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hizb);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hizb);
        }

        // GET: Hizbs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hizb = await _context.Hizbs.FindAsync(id);
            if (hizb == null)
            {
                return NotFound();
            }
            return View(hizb);
        }

        // POST: Hizbs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Numero,Nom,Description")] Hizb hizb)
        {
            if (id != hizb.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hizb);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HizbExists(hizb.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hizb);
        }

        // GET: Hizbs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hizb = await _context.Hizbs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hizb == null)
            {
                return NotFound();
            }

            return View(hizb);
        }

        // POST: Hizbs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hizb = await _context.Hizbs.FindAsync(id);
            _context.Hizbs.Remove(hizb);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HizbExists(int id)
        {
            return _context.Hizbs.Any(e => e.Id == id);
        }
    }
}

Ecole Coranique/Controllers/TrackingController.cs
using Ecole_Coranique.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Ecole_Coranique.Controllers
{
    public class TrackingController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TrackingController(ApplicationDbContext context) {
            _context = context;
        }
        public async Task<IActionResult> AdminTrack() {
            return View(await _context.Enseignants.ToListAsync());
        }
        public async Task<IActionResult> TeacherTrack(int? id) {
            if (id == null) {
                return NotFound();
            }
            var enseignant = await _context.Enseignants
                .Include(x => x.EnseignantGroupes)
                .ThenInclude(x => x.GroupeEtudiants)
                .FirstOrDefaultAsync(x => x.Id == id);
            if (enseignant == null) {
                return NotFound();
            }
            return View(enseignant);
        }
        public async Task<IActionResult> StudentTrack(int? id) {
            if (id == null) {
                return NotFound();
            }
            var etudiant = await _context.Etudiants
                .Include(e => e.Groupe)
                .Include(e => e.EtudiantAbsences)
                .Include(e => e.EtudiantRevisions)
                .ThenInclude(r => r.Hizb)
                .Include(e => e.EtudiantRevisions)
                .ThenInclude(r => r.Huitieme)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (etudiant == null) {
                return NotFound();
            }
            return View(etudiant);
        }
    }
}

Ecole Coranique/Views/Shared/_AdminLinks.cshtml
<ul class="navbar-nav flex-grow-1">
	<li class="nav-item">
		<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">الصفحة الرئيسية</a>
	</li>
	<li>
		<a class="nav-link text-dark" asp-area="" asp-controller="Tracking" asp-action="AdminTrack">مسار المدرسة</a>
	</li>
	<li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">الأنشطة</a>
		<div class="dropdown-menu">
			<a class="nav-link text-dark" asp-area="" asp-controller="Revisions" asp-action="Index">مراجعات</a>
			<a class="nav-link text-dark" asp-area="" asp-controller="Absences" asp-action="Index">غيابات</a>
			<a class="nav-link text-dark" asp-area="" asp-controller="Groupes" asp-action="Index">مجموعات</a>
		</div>
	</li>
	<li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">الأشخاص</a>
		<div class="dropdown-menu">
			<a class="nav-link text-dark" asp-area="" asp-controller="Etudiants" asp-action="Index">طلاب</a>
			<a class="nav-link text-dark" asp-area="" asp-controller="Enseignants" asp-action="Index">مدرسين</a>
		</div>
	</li>
	<li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">الإعدادات</a>
		<div class="dropdown-menu">
			<a class="nav-link text-dark" asp-area="" asp-controller="Huitiemes" asp-action="Index">أثمان</a>
			<a class="nav-link text-dark" asp-area="" asp-controller="Hizbs" asp-action="Index">أحزاب</a>
			<a class="nav-link text-dark" asp-area="" asp-controller="IdentificationEtudiants" asp-action="Index">تحديد الطلاب</a>
			<a class="nav-link text-dark" asp-area="" asp-controller="IdentificationEnseignants" asp-action="Index">تحديد المدرسين</a>
			<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">خصوصية</a>
		</div>
	</li>
</ul>

Ecole Coranique/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - المدرسة القرآنية</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-minty-rtl.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Ecole_Coranique.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<partial name="_Navbar" />
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - المدرسة القرآنية - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Ecole Coranique/Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
	<div class="container-fluid">
		<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">المدرسة القرآنية</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
				aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
			@if ((await AuthorizationService.AuthorizeAsync(User, AppPolicyName.Administration)).Succeeded) {
				<partial name="_AdminLinks"/>
			}
			<partial name="_LoginPartial" />
		</div>
	</div>
</nav>